import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { confirm } from '@inquirer/prompts';
import type { AgentId } from './types.js';
import { getShimsDir, getVersionsDir, ensureAgentsDir } from './state.js';
export { getShimsDir };
import { AGENTS } from './agents.js';

/**
 * Generate the shim script content for an agent.
 *
 * The shim resolves the version (project manifest -> global default) and execs
 * the appropriate binary. Config isolation is handled via symlinks:
 * ~/.{agent} -> ~/.agents/versions/{agent}/{version}/home/.{agent}/
 *
 * The symlink is updated by `agents use` when switching versions.
 */
function generateShimScript(agent: AgentId): string {
  const agentConfig = AGENTS[agent];
  const cliCommand = agentConfig.cliCommand;

  return `#!/bin/bash
# Auto-generated by agents-cli - do not edit
# Shim for ${agentConfig.name}

AGENTS_DIR="$HOME/.agents"
AGENT="${agent}"
CLI_COMMAND="${cliCommand}"

# Resolve version from global config only
resolve_version() {
  local global_config="$AGENTS_DIR/agents.yaml"
  if [ -f "$global_config" ]; then
    awk -v agent="$AGENT" '
      /^agents:/ { in_agents=1; next }
      in_agents && /^[^ ]/ { in_agents=0 }
      in_agents && $0 ~ "^  " agent ":" { gsub(/.*:[[:space:]]*["'"'"']?|["'"'"']?[[:space:]]*$/, ""); print; exit }
    ' "$global_config"
  fi
}

VERSION=$(resolve_version)

if [ -z "$VERSION" ]; then
  echo "agents: no version of $AGENT configured" >&2
  echo "Run: agents add $AGENT@<version>" >&2
  exit 1
fi

VERSION_DIR="$AGENTS_DIR/versions/$AGENT/$VERSION"
BINARY="$VERSION_DIR/node_modules/.bin/$CLI_COMMAND"

if [ ! -x "$BINARY" ]; then
  echo "agents: $AGENT@$VERSION not installed" >&2
  echo "Run: agents add $AGENT@$VERSION" >&2
  exit 1
fi

exec "$BINARY" "$@"
`;
}

/**
 * Create a shim for an agent.
 */
export function createShim(agent: AgentId): string {
  ensureAgentsDir();
  const shimsDir = getShimsDir();
  const agentConfig = AGENTS[agent];
  const shimPath = path.join(shimsDir, agentConfig.cliCommand);

  const script = generateShimScript(agent);
  fs.writeFileSync(shimPath, script, { mode: 0o755 });

  return shimPath;
}

/**
 * Remove the shim for an agent.
 */
export function removeShim(agent: AgentId): boolean {
  const shimsDir = getShimsDir();
  const agentConfig = AGENTS[agent];
  const shimPath = path.join(shimsDir, agentConfig.cliCommand);

  if (fs.existsSync(shimPath)) {
    fs.unlinkSync(shimPath);
    return true;
  }

  return false;
}

/**
 * Generate a versioned alias script that directly execs a specific version.
 * e.g., claude@2.0.65 -> directly runs that version's binary
 */
function generateVersionedAliasScript(agent: AgentId, version: string): string {
  const agentConfig = AGENTS[agent];

  return `#!/bin/bash
# Auto-generated by agents-cli - do not edit
# Direct alias for ${agentConfig.name}@${version}

BINARY="$HOME/.agents/versions/${agent}/${version}/node_modules/.bin/${agentConfig.cliCommand}"

if [ ! -x "$BINARY" ]; then
  echo "agents: ${agent}@${version} not installed" >&2
  exit 1
fi

exec "$BINARY" "$@"
`;
}

/**
 * Create a versioned alias for a specific agent version.
 * e.g., claude@2.0.65
 */
export function createVersionedAlias(agent: AgentId, version: string): string {
  ensureAgentsDir();
  const shimsDir = getShimsDir();
  const agentConfig = AGENTS[agent];
  const aliasPath = path.join(shimsDir, `${agentConfig.cliCommand}@${version}`);

  const script = generateVersionedAliasScript(agent, version);
  fs.writeFileSync(aliasPath, script, { mode: 0o755 });

  return aliasPath;
}

/**
 * Remove a versioned alias for a specific agent version.
 */
export function removeVersionedAlias(agent: AgentId, version: string): boolean {
  const shimsDir = getShimsDir();
  const agentConfig = AGENTS[agent];
  const aliasPath = path.join(shimsDir, `${agentConfig.cliCommand}@${version}`);

  if (fs.existsSync(aliasPath)) {
    fs.unlinkSync(aliasPath);
    return true;
  }

  return false;
}

/**
 * Check if a versioned alias exists.
 */
export function versionedAliasExists(agent: AgentId, version: string): boolean {
  const shimsDir = getShimsDir();
  const agentConfig = AGENTS[agent];
  const aliasPath = path.join(shimsDir, `${agentConfig.cliCommand}@${version}`);
  return fs.existsSync(aliasPath);
}

/**
 * Get the path to the agent's config directory in HOME.
 * e.g., ~/.claude for claude, ~/.codex for codex
 */
function getAgentConfigPath(agent: AgentId): string {
  const agentConfig = AGENTS[agent];
  const home = process.env.AGENTS_REAL_HOME || os.homedir();
  return agentConfig.configDir.replace(os.homedir(), home);
}

/**
 * Get the path to the version's config directory.
 * e.g., ~/.agents/versions/claude/2.0.65/home/.claude/
 */
function getVersionConfigPath(agent: AgentId, version: string): string {
  const agentConfig = AGENTS[agent];
  const versionsDir = getVersionsDir();
  const configDirName = `.${agent}`; // .claude, .codex, etc.
  return path.join(versionsDir, agent, version, 'home', configDirName);
}

/**
 * Switch the agent's config symlink to point to a specific version.
 * e.g., ~/.claude -> ~/.agents/versions/claude/2.0.65/home/.claude/
 *
 * Returns: { success: boolean, migrated?: boolean, error?: string }
 */
export async function switchConfigSymlink(
  agent: AgentId,
  version: string
): Promise<{ success: boolean; migrated?: boolean; error?: string }> {
  const configPath = getAgentConfigPath(agent);
  const versionConfigPath = getVersionConfigPath(agent, version);

  // Ensure version config directory exists
  if (!fs.existsSync(versionConfigPath)) {
    fs.mkdirSync(versionConfigPath, { recursive: true });
  }

  try {
    const stat = fs.lstatSync(configPath);

    if (stat.isSymbolicLink()) {
      // Already a symlink - check if it points to the correct target
      const currentTarget = fs.readlinkSync(configPath);
      const resolvedCurrent = path.resolve(path.dirname(configPath), currentTarget);
      const resolvedTarget = path.resolve(versionConfigPath);
      if (resolvedCurrent === resolvedTarget) {
        // Already pointing to correct target, no-op
        return { success: true };
      }
      // Different target - update it
      fs.unlinkSync(configPath);
      fs.symlinkSync(versionConfigPath, configPath);
      return { success: true };
    } else if (stat.isDirectory()) {
      // Real directory exists - migrate it to this version's config
      // Move contents to version config, then create symlink
      const tempPath = `${configPath}.backup.${Date.now()}`;
      fs.renameSync(configPath, tempPath);

      // Copy contents from backup to version config (with prompts for conflicts)
      await copyDirContents(tempPath, versionConfigPath);

      // Create symlink
      fs.symlinkSync(versionConfigPath, configPath);

      // Remove backup
      fs.rmSync(tempPath, { recursive: true, force: true });

      return { success: true, migrated: true };
    } else {
      return { success: false, error: `${configPath} exists but is not a directory or symlink` };
    }
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      // Config path doesn't exist - create symlink
      fs.symlinkSync(versionConfigPath, configPath);
      return { success: true };
    }
    return { success: false, error: (err as Error).message };
  }
}

/**
 * Get the current config symlink target version, if any.
 */
export function getConfigSymlinkVersion(agent: AgentId): string | null {
  const configPath = getAgentConfigPath(agent);

  try {
    const stat = fs.lstatSync(configPath);
    if (!stat.isSymbolicLink()) {
      return null;
    }

    const target = fs.readlinkSync(configPath);
    // Extract version from path like ~/.agents/versions/claude/2.0.65/home/.claude
    const match = target.match(/versions\/[^/]+\/([^/]+)\/home/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

/**
 * Copy directory contents with conflict prompts.
 * When a file exists in dest, backs it up and asks user whether to overwrite.
 */
async function copyDirContents(src: string, dest: string): Promise<void> {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      await copyDirContents(srcPath, destPath);
    } else if (entry.isSymbolicLink()) {
      const linkTarget = fs.readlinkSync(srcPath);
      if (fs.existsSync(destPath)) {
        fs.unlinkSync(destPath);
      }
      fs.symlinkSync(linkTarget, destPath);
    } else {
      // File - check for conflict
      if (fs.existsSync(destPath)) {
        // Back up dest file
        fs.copyFileSync(destPath, `${destPath}.backup`);

        // Ask user
        const overwrite = await confirm({
          message: `${entry.name} exists in version home. Overwrite with your current config?`,
          default: true,
        });

        if (!overwrite) {
          continue; // Keep dest, skip copying src
        }
      }
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * Check if shim exists for an agent.
 */
export function shimExists(agent: AgentId): boolean {
  const shimsDir = getShimsDir();
  const agentConfig = AGENTS[agent];
  const shimPath = path.join(shimsDir, agentConfig.cliCommand);
  return fs.existsSync(shimPath);
}

/**
 * Get the path to the shim for an agent.
 */
export function getShimPath(agent: AgentId): string {
  const shimsDir = getShimsDir();
  const agentConfig = AGENTS[agent];
  return path.join(shimsDir, agentConfig.cliCommand);
}

/**
 * Check if shims directory is in PATH.
 */
export function isShimsInPath(): boolean {
  const shimsDir = getShimsDir();
  const pathDirs = (process.env.PATH || '').split(path.delimiter);
  return pathDirs.some((dir) => path.resolve(dir) === path.resolve(shimsDir));
}

/**
 * Get the shell rc file path for the current shell.
 */
function getShellRcFile(): { rcFile: string; rcPath: string; shell: string } {
  const shell = process.env.SHELL || '/bin/bash';
  const shellName = path.basename(shell);

  let rcFile: string;
  switch (shellName) {
    case 'zsh':
      rcFile = '.zshrc';
      break;
    case 'fish':
      rcFile = '.config/fish/config.fish';
      break;
    case 'bash':
    default:
      rcFile = '.bashrc';
      break;
  }

  return {
    rcFile,
    rcPath: path.join(os.homedir(), rcFile),
    shell: shellName,
  };
}

/**
 * Get shell configuration instructions for adding shims to PATH.
 */
export function getPathSetupInstructions(): string {
  const shimsDir = getShimsDir();
  const { rcFile, shell } = getShellRcFile();

  if (shell === 'fish') {
    return `Add to ~/.config/fish/config.fish:
  fish_add_path ${shimsDir}`;
  }

  return `Add to ~/${rcFile} (BEFORE any nvm/node setup):
  export PATH="${shimsDir}:$PATH"

IMPORTANT: Shims must come FIRST in PATH to override global installs.

Then restart your shell or run:
  source ~/${rcFile}`;
}

/**
 * Add shims directory to shell PATH configuration.
 * Returns true if added, false if already present or failed.
 */
export function addShimsToPath(): { success: boolean; alreadyPresent?: boolean; rcFile?: string; error?: string } {
  const shimsDir = getShimsDir();
  const { rcFile, rcPath, shell } = getShellRcFile();

  // Read current rc file content
  let content = '';
  try {
    if (fs.existsSync(rcPath)) {
      content = fs.readFileSync(rcPath, 'utf-8');
    }
  } catch (err) {
    return { success: false, error: `Could not read ${rcFile}: ${(err as Error).message}` };
  }

  // Check if shims path already in file
  if (content.includes(shimsDir) || content.includes('$HOME/.agents/shims')) {
    return { success: true, alreadyPresent: true, rcFile };
  }

  // Generate the export line
  let exportLine: string;
  if (shell === 'fish') {
    exportLine = `\n# agents-cli: version-managed agent CLIs\nfish_add_path ${shimsDir}\n`;
  } else {
    exportLine = `\n# agents-cli: version-managed agent CLIs\nexport PATH="${shimsDir}:$PATH"\n`;
  }

  // Find insertion point - BEFORE nvm/node setup if possible
  // Look for common patterns that should come AFTER our shims
  const insertBeforePatterns = [
    /^export NVM_DIR=/m,
    /^source.*nvm/m,
    /^\[ -s.*nvm/m,
    /^eval.*fnm/m,
    /^export PATH.*node/m,
    /^export PATH.*npm/m,
  ];

  let insertIndex = -1;
  for (const pattern of insertBeforePatterns) {
    const match = content.match(pattern);
    if (match && match.index !== undefined) {
      // Find start of this line
      let lineStart = match.index;
      while (lineStart > 0 && content[lineStart - 1] !== '\n') {
        lineStart--;
      }
      if (insertIndex === -1 || lineStart < insertIndex) {
        insertIndex = lineStart;
      }
    }
  }

  // Write the updated content
  try {
    let newContent: string;
    if (insertIndex > 0) {
      // Insert before nvm/node setup
      newContent = content.slice(0, insertIndex) + exportLine + content.slice(insertIndex);
    } else {
      // Append to end
      newContent = content + exportLine;
    }
    fs.writeFileSync(rcPath, newContent, 'utf-8');
    return { success: true, rcFile };
  } catch (err) {
    return { success: false, error: `Could not write ${rcFile}: ${(err as Error).message}` };
  }
}

/**
 * Create shims for all installed agents.
 */
export function ensureAllShims(): void {
  const versionsDir = getVersionsDir();
  if (!fs.existsSync(versionsDir)) {
    return;
  }

  const entries = fs.readdirSync(versionsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory() && AGENTS[entry.name as AgentId]) {
      const agent = entry.name as AgentId;
      const agentVersionsDir = path.join(versionsDir, agent);
      const versions = fs.readdirSync(agentVersionsDir, { withFileTypes: true })
        .filter((e) => e.isDirectory());

      if (versions.length > 0 && !shimExists(agent)) {
        createShim(agent);
      }
    }
  }
}

/**
 * Resource diff between two versions.
 */
export interface ResourceDiff {
  commands: string[];  // names in current but not in target
  skills: string[];
  hooks: string[];
  memory: { file: string; currentLines: number; targetLines: number }[];
  mcp: string[];  // server names in current but not in target
}

/**
 * Compare resources between two versions.
 * Returns resources that exist in currentVersion but not in targetVersion.
 */
export function compareVersionResources(
  agent: AgentId,
  currentVersion: string,
  targetVersion: string
): ResourceDiff {
  const agentConfig = AGENTS[agent];
  const currentPath = getVersionConfigPath(agent, currentVersion);
  const targetPath = getVersionConfigPath(agent, targetVersion);

  const diff: ResourceDiff = {
    commands: [],
    skills: [],
    hooks: [],
    memory: [],
    mcp: [],
  };

  // Helper to list directory contents (names only)
  const listDir = (dir: string): string[] => {
    if (!fs.existsSync(dir)) return [];
    try {
      return fs.readdirSync(dir).filter(f => !f.startsWith('.'));
    } catch {
      return [];
    }
  };

  // Helper to count lines in a file
  const countLines = (filePath: string): number => {
    if (!fs.existsSync(filePath)) return 0;
    try {
      return fs.readFileSync(filePath, 'utf-8').split('\n').length;
    } catch {
      return 0;
    }
  };

  // Compare commands
  const currentCommands = listDir(path.join(currentPath, agentConfig.commandsSubdir));
  const targetCommands = new Set(listDir(path.join(targetPath, agentConfig.commandsSubdir)));
  diff.commands = currentCommands.filter(c => !targetCommands.has(c)).map(c => c.replace(/\.(md|toml)$/, ''));

  // Compare skills
  const currentSkills = listDir(path.join(currentPath, 'skills'));
  const targetSkills = new Set(listDir(path.join(targetPath, 'skills')));
  diff.skills = currentSkills.filter(s => !targetSkills.has(s));

  // Compare hooks
  const currentHooks = listDir(path.join(currentPath, 'hooks'));
  const targetHooks = new Set(listDir(path.join(targetPath, 'hooks')));
  diff.hooks = currentHooks.filter(h => !targetHooks.has(h));

  // Compare memory files (instructionsFile like CLAUDE.md)
  const memoryFile = agentConfig.instructionsFile;
  const currentMemoryPath = path.join(currentPath, memoryFile);
  const targetMemoryPath = path.join(targetPath, memoryFile);
  const currentLines = countLines(currentMemoryPath);
  const targetLines = countLines(targetMemoryPath);
  if (currentLines > 0 && currentLines !== targetLines) {
    diff.memory.push({ file: memoryFile, currentLines, targetLines });
  }

  // Compare MCP servers (from settings.json)
  const readMcpServers = (configPath: string): string[] => {
    const settingsPath = path.join(configPath, 'settings.json');
    if (!fs.existsSync(settingsPath)) return [];
    try {
      const settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
      return Object.keys(settings.mcpServers || {});
    } catch {
      return [];
    }
  };

  const currentMcp = readMcpServers(currentPath);
  const targetMcp = new Set(readMcpServers(targetPath));
  diff.mcp = currentMcp.filter(m => !targetMcp.has(m));

  return diff;
}

/**
 * Check if a ResourceDiff has any differences.
 */
export function hasResourceDiff(diff: ResourceDiff): boolean {
  return (
    diff.commands.length > 0 ||
    diff.skills.length > 0 ||
    diff.hooks.length > 0 ||
    diff.memory.length > 0 ||
    diff.mcp.length > 0
  );
}

/**
 * Copy resources from one version to another.
 * Only copies resources listed in the diff (i.e., ones missing in target).
 */
export function copyResourcesToVersion(
  agent: AgentId,
  fromVersion: string,
  toVersion: string,
  diff: ResourceDiff
): void {
  const agentConfig = AGENTS[agent];
  const fromPath = getVersionConfigPath(agent, fromVersion);
  const toPath = getVersionConfigPath(agent, toVersion);

  // Helper to copy a file or directory
  const copyItem = (srcDir: string, destDir: string, name: string): void => {
    const srcPath = path.join(srcDir, name);
    const destPath = path.join(destDir, name);
    if (!fs.existsSync(srcPath)) return;

    fs.mkdirSync(destDir, { recursive: true });

    const stat = fs.statSync(srcPath);
    if (stat.isDirectory()) {
      copyDirContents(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  };

  // Copy missing commands
  const commandsSubdir = agentConfig.commandsSubdir;
  const ext = agentConfig.format === 'toml' ? '.toml' : '.md';
  for (const cmd of diff.commands) {
    copyItem(
      path.join(fromPath, commandsSubdir),
      path.join(toPath, commandsSubdir),
      `${cmd}${ext}`
    );
  }

  // Copy missing skills
  for (const skill of diff.skills) {
    copyItem(path.join(fromPath, 'skills'), path.join(toPath, 'skills'), skill);
  }

  // Copy missing hooks
  for (const hook of diff.hooks) {
    copyItem(path.join(fromPath, 'hooks'), path.join(toPath, 'hooks'), hook);
  }

  // Copy memory file if different
  for (const mem of diff.memory) {
    const srcPath = path.join(fromPath, mem.file);
    const destPath = path.join(toPath, mem.file);
    if (fs.existsSync(srcPath)) {
      fs.copyFileSync(srcPath, destPath);
    }
  }

  // Merge MCP servers into target settings.json
  if (diff.mcp.length > 0) {
    const fromSettingsPath = path.join(fromPath, 'settings.json');
    const toSettingsPath = path.join(toPath, 'settings.json');

    if (fs.existsSync(fromSettingsPath)) {
      try {
        const fromSettings = JSON.parse(fs.readFileSync(fromSettingsPath, 'utf-8'));
        let toSettings: Record<string, unknown> = {};

        if (fs.existsSync(toSettingsPath)) {
          toSettings = JSON.parse(fs.readFileSync(toSettingsPath, 'utf-8'));
        }

        if (!toSettings.mcpServers) {
          toSettings.mcpServers = {};
        }

        for (const serverName of diff.mcp) {
          if (fromSettings.mcpServers?.[serverName]) {
            (toSettings.mcpServers as Record<string, unknown>)[serverName] = fromSettings.mcpServers[serverName];
          }
        }

        fs.writeFileSync(toSettingsPath, JSON.stringify(toSettings, null, 2));
      } catch {
        // Ignore JSON parse errors
      }
    }
  }
}
